package com.pluralsight.cxfdemo.orders;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.pluralsight.schema.order.OrderInquiryResponseType;
import com.pluralsight.schema.order.OrderInquiryType;
import com.pluralsight.service.orders.Orders;

/**
 * Controller for processing orders through the Orders web service.
 * 
 * @author Michael Hoffman, Pluralsight
 * 
 */
// Spring controller annotation mapping the URL path to /processOrderPlacement
@Controller("/processOrderPlacement")
public class OrdersController {

   // Orders web service interface generated by the Maven code generation
   // plug-in
   @Autowired
   private Orders orders;

   /**
    * Controller method called on a GET request type to /processOrderPlacement.
    * Calls the orders web service and then returns the order status in the
    * response.
    * 
    * @param model
    * @return
    * @throws Exception
    */
   @RequestMapping(method = RequestMethod.GET)
   public String processOrderPlacement(ModelMap model) throws Exception {
      // Create an OrderInquiryType request object and populate it.
      OrderInquiryType orderInquiry = new com.pluralsight.schema.order.ObjectFactory()
            .createOrderInquiryType();
      orderInquiry.setAccountId(1234);
      orderInquiry.setEan13(1234567890123L);
      orderInquiry.setOrderQuantity(2);
      orderInquiry.setUniqueOrderId(999);
      // Call the Orders web service.
      OrderInquiryResponseType response = orders
            .processOrderPlacement(orderInquiry);
      // Set the order status on the model.
      model.addAttribute("orderStatus", response.getOrder().getOrderStatus()
            .value());

      // View we are returning to, in this case processOrderPlacement.jsp
      return "processOrderPlacement";
   }
}
