package com.pluralsight.cxfdemo.orders;

import javax.jws.WebService;

import org.springframework.beans.factory.annotation.Autowired;

import com.pluralsight.schema.order.OrderInquiryResponseType;
import com.pluralsight.schema.order.OrderInquiryType;
import com.pluralsight.service.orders.Orders;

/**
 * This is the default implementation of the Orders interface generated by the
 * Maven CXF code-gen plugin. The class is annotated with the JAX-WS web service
 * annotation. The values for the port name and service name come from the
 * service and port WSDL elements. The endpoint interface value is the fully
 * qualified name for the Orders interface.
 * 
 * @author Michael Hoffman, Pluralsight
 * 
 */
@WebService(portName = "OrdersSOAP", serviceName = "Orders",
      endpointInterface = "com.pluralsight.service.orders.Orders",
      targetNamespace = "http://www.pluralsight.com/service/Orders/")
public class DefaultOrdersEndpoint implements Orders {

   // Autowire allows Spring to inject the order service containing core
   // business logic.
   @Autowired
   private OrderService orderService;

   @Override
   public OrderInquiryResponseType processOrderPlacement(
         OrderInquiryType orderInquiry) {

      // This method is the implementation for processing an order. It is
      // responsible for processing the message. At this time, it just routes
      // the call to our business logic service to complete the task.
      OrderInquiryResponseType response = orderService.processOrder(
            orderInquiry.getUniqueOrderId(), orderInquiry.getOrderQuantity(),
            orderInquiry.getAccountId(), orderInquiry.getEan13());
      return response;
   }

}
