package com.pluralsight.service.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * The port type of the WSDL is the first element we will focus on. This element is comparable 
 * 			to an interface. It defines the type or types of services that are available. As part of 
 * 			generation, the port type has been given the name Orders to uniquely identify it in the document.
 * 		
 *
 * This class was generated by Apache CXF 2.7.8
 * 2016-10-18T12:52:44.547+05:30
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://www.pluralsight.com/service/Orders/", name = "Orders")
@XmlSeeAlso({com.pluralsight.schema.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebMethod(operationName = "ProcessOrderPlacement", action = "http://www.pluralsight.com/service/Orders/ProcessOrderPlacement")
    @WebResult(name = "orderInquiryResponse", targetNamespace = "http://www.pluralsight.com/schema/Order", partName = "orderInquiryResponse")
    public com.pluralsight.schema.order.OrderInquiryResponseType processOrderPlacement(
        @WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://www.pluralsight.com/schema/Order")
        com.pluralsight.schema.order.OrderInquiryType orderInquiry
    );
}
